---
- name: Check whether Hugo is installed
  ansible.builtin.command: hugo version
  register: hugo_installed
  changed_when: false
  ignore_errors: true
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Add hugo repo to the system
  ansible.builtin.yum_repository:
    name: hugo
    description: Copr repo for hugo owned by daftaupe
    baseurl: |
      'https://download.copr.fedorainfracloud.org/results/daftaupe/hugo/epel-{{ ansible_distribution_major_version }}-$basearch/'
    gpgcheck: yes
    gpgkey: |
      https://download.copr.fedorainfracloud.org/results/daftaupe/hugo/pubkey.gpg
  when: hugo_installed is failed

- name: Install Hugo
  ansible.builtin.package:
    name: hugo
    state: present
  when: hugo_installed is failed
