---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether hugo is installed
      ansible.builtin.command: hugo version
      register: hugo_version
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show Hugo version
      ansible.builtin.debug:
        var: hugo_version

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
